// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNVwpGBz1HUQs8Y9Ab-I_Nu4pPbeixmY',
    appId: '1:785469951781:web:e5b45a44c5ec5f44d0d4cc',
    messagingSenderId: '785469951781',
    projectId: 'pixelprowess69',
    authDomain: 'pixelprowess69.firebaseapp.com',
    storageBucket: 'pixelprowess69.appspot.com',
    measurementId: 'G-TZ5WZEQPZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvajcaDi-GDoZU4O8MyBsLeK0Ay56VKqw',
    appId: '1:785469951781:android:6308e24ac1dbf4b0d0d4cc',
    messagingSenderId: '785469951781',
    projectId: 'pixelprowess69',
    storageBucket: 'pixelprowess69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmr0kiPIJjqkTJUNikpzUZXis-qgjgAZA',
    appId: '1:785469951781:ios:74f3a327e60d9c33d0d4cc',
    messagingSenderId: '785469951781',
    projectId: 'pixelprowess69',
    storageBucket: 'pixelprowess69.appspot.com',
    iosBundleId: 'com.example.pixelprowess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmr0kiPIJjqkTJUNikpzUZXis-qgjgAZA',
    appId: '1:785469951781:ios:f4ee2cd8c8be2a86d0d4cc',
    messagingSenderId: '785469951781',
    projectId: 'pixelprowess69',
    storageBucket: 'pixelprowess69.appspot.com',
    iosBundleId: 'com.example.pixelprowess.RunnerTests',
  );
}
